### ISSUE TITLE
calwebb_spec3 crashes with "invalid shape in fixed-type tuple: dimension does not fit into a C int"

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7274]
_Issue [JP-2900](https://jira.stsci.edu/browse/JP-2900) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

fileset [jw01243-o001_20220822t204950_spec3_001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01243-o001_20220822t204950_spec3_001_1662166543.755487&fileset_name=jw01243-o001_20220822t204950_spec3_001&dag_name=LEVEL_3) crashed right after finishing the combine_1d step for one of the source-based spectral extractions in this nrc_wfss dataset. it appeared to crash while attempting to write out the output product. the error message _" invalid shape in fixed-type tuple: dimension does not fit into a C int"_ is very similar to that seen previously for nrs_dark in JP-2251 and  JP-2119.
```java
2022-09-04 00:37:07,559 - CRDS - DEBUG - Final effective context is 'jwst_0968.pmap'
2022-09-04 00:37:07,559 - CRDS - DEBUG - Computing best references locally.
2022-09-04 00:37:07,561 - CRDS - DEBUG - Bestrefs header:
{'META.EXPOSURE.NOUTPUTS [NOUTPUTS]': '4.0',
'META.EXPOSURE.READPATT [READPATT]': 'SHALLOW4',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRC_WFSS',
'META.INSTRUMENT.CHANNEL [CHANNEL]': 'LONG',
'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRCALONG',
'META.INSTRUMENT.FILTER [FILTER]': 'F356W',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'UNDEFINED',
'META.INSTRUMENT.MODULE [MODULE]': 'A',
'META.INSTRUMENT.NAME [INSTRUME]': 'NIRCAM',
'META.INSTRUMENT.PUPIL [PUPIL]': 'GRISMR',
'META.OBSERVATION.DATE [DATE-OBS]': '2022-08-22',
'META.OBSERVATION.TIME [TIME-OBS]': '13:08:23.206',
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'F',
'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED',
'REFTYPE': 'UNDEFINED'}
2022-09-04 00:37:07,561 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_nircam_apcorr_0003.fits'
2022-09-04 00:37:07,570 - stpipe.Spec3Pipeline.extract_1d - INFO - Using APCORR file /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_apcorr_0003.fits
2022-09-04 00:37:07,570 - stpipe.Spec3Pipeline.extract_1d - INFO - No EXTRACT1D reference file will be used
2022-09-04 00:37:07,625 - stpipe.Spec3Pipeline.extract_1d - INFO - Working on slit 2464
<snip>
...

2022-09-04 00:38:58,785 - stpipe.Spec3Pipeline.combine_1d - WARNING - 22 output pixel numbers were NaN
2022-09-04 00:38:58,993 - stpipe.Spec3Pipeline.combine_1d - INFO - Saved model in jw01243-o001_s02464_nircam_f356w-grismr_c1d.fits
2022-09-04 00:38:58,993 - stpipe.Spec3Pipeline.combine_1d - INFO - Step combine_1d done
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/bin/strun", line 28, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 179, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/cmdline.py", line 349, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 485, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec3.py", line 214, in process
self.save_model(result, 'cal')
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 981, in save_model
output_path = model.save(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/datamodels/source_container.py", line 75, in save
save_model_func(self.multiexposure, output_file=path)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 993, in save_model
output_path = model.save(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stdatamodels/model_base.py", line 523, in save
self.to_fits(output_path, *args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stdatamodels/model_base.py", line 649, in to_fits
ff.write_to(init, *args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/fits_embed.py", line 342, in write_to
self._update_asdf_extension(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/fits_embed.py", line 325, in _update_asdf_extension
self._hdulist.append(self._create_hdu(buff, use_image_hdu))
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/fits_embed.py", line 304, in _create_hdu
column = fits.Column(array=data, format=fmt, name="ASDF_METADATA")
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/column.py", line 663, in __init__
array = self._convert_to_valid_data_type(array)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/column.py", line 1341, in _convert_to_valid_data_type
dtype = np.dtype(numpy_format).base
ValueError: invalid shape in fixed-type tuple: dimension does not fit into a C int.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':
invalid shape in fixed-type tuple: dimension does not fit into a C
int.
----------------------------------------------------------------------
2022247004337-E-ERROR-/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec3.cfg FAILED (exit=1) on jw01243-o001_20220822t204950_spec3_001_asn.json. ```
(full logs at  /ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01243-o001_20220822t204950_spec3_001_1662166543.755487)

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=605285#comment-605285):_

asn file attached

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=607599#comment-607599):_

Critical priority assigned since the issue is causing the operational pipeline to crash for this data

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=607811#comment-607811):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Do you know if this dataset was run on a high memory node? I attempted to reproduce the error and ran out of disk space before completing level 3 processing, so I'm going to attempt to target the specific source to debug, but I wouldn't be surprised if this was a memory or storage error manifested in a strange way.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=607842#comment-607842):_

yes, this was run in a high memory node. it initially failed due to memory error, then i rescued it into a high memory node, where it crashed with this error

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=608253#comment-608253):_

I think this problem is originating from the creation of the FITS extension holding the ASDF metadata - the size of the byte array is greater than the size of a C int (maybe?). I'm trying to nail it down, but if this is correct, I don't really know what the path forward would be. [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=608381#comment-608381):_

Bug found:

The output cal file attempts to store so much data in the "ASDF_METADATA" FITS extension that the length of the buffer fed into the astropy.io.fits.Column is too large to store in a C integer.

Relevant ASDF code here: <https://github.com/asdf-format/asdf/blob/bea51b130cf51bfdca72fb12e91f45ffd260679f/asdf/fits_embed.py#L296-L305>

MWE:
```python
>>> dat = np.zeros(2150000000)
>>> fmt = f"{len(dat)}B"
>>> column = fits.Column(array=dat, format=fmt, name="ASDF_METADATA")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tpauly/miniconda3/envs/jwstdev/lib/python3.9/site-packages/astropy/io/fits/column.py", line 663, in __init__
    array = self._convert_to_valid_data_type(array)
  File "/Users/tpauly/miniconda3/envs/jwstdev/lib/python3.9/site-packages/astropy/io/fits/column.py", line 1341, in _convert_to_valid_data_type
    dtype = np.dtype(numpy_format).base
ValueError: invalid shape in fixed-type tuple: dimension does not fit into a C int.
```

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) I'm not sure if this is something we would want to avoid internally - creating an extension of this size that claims to hold only metadata seems like a stretch - or if this is something that ASDF needs to catch and avoid more gracefully.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=608446#comment-608446):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) I investigated this a little bit and determined that this is likely an astropy bug. I have created an astropy issue in an attempt to resolve this: <https://github.com/astropy/astropy/issues/13748.>

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=609064#comment-609064):_

Apparently, this is a long-time astropy bug, see astropy/astropy#1840

The basic suggestion is to divide up everything into multiple tables.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=610892#comment-610892):_

[William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) This seems like an issue in how datamodels are attempting to store the asdf metadata - it seems like an issue that might repeat for users of asdf's fits embedding. Should I open an ASDF issue regarding this problem?

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=610902#comment-610902):_

Fits embedding is only supported for JWST (we are planning on moving all asdf-in-fits support entirely out of ASDF), so this is purely a JWST issue.

 

The main issue is JWST is attempting to store data in ASDF which has more entries (columns in this case if I understand it) than an unsigned 32bit integer (4,294,967,295). This runs into fundamental limitations of the astropy fits library itself, due to a limitation of numpy (representation of dtype array index with 32bit unsigned integers). The basic suggestion is to divide the data up into multiple tables, each with fewer than 4,294,967,295 entries.

**Comment by nden** [comment]
JP ticket was resolved

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=627295#comment-627295):_

In case you need another example, another case of this error occurred during the reprocessing of PID 1286:

[jw01286-o001_20230201t231614_spec3_00002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01286-o001_20230201t231614_spec3_00002_1675349443.185330&fileset_name=jw01286-o001_20230201t231614_spec3_00002&dag_name=REPRO_LEVEL_3)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=627330#comment-627330):_

Yes, it's been fixed in DMS B9.1, but Ops isn't running that version yet, so they're still seeing errors.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=637404#comment-637404):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Has this been tested yet with B9.1.x?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2900?focusedCommentId=637430#comment-637430):_

yes, we were able to run jw01243-o001 with b9.1.1 2023mar16 and this error was no longer seen.
