### ISSUE TITLE
niriss soss schema not found

### ISSUE THREAD

**Issue by braingram** [spacetelescope/jwst#7401]
Running calwebb_spec2 on atoca_extras_rateints.fits (from the regression test artifacts) results in a warning:
```python
2022-12-16 11:43:36,918 - stpipe.Spec2Pipeline - WARNING - /Users/bgraham/.pyenv/versions/jwst_stpipe/lib/python3.10/site-packages/asdf/schema.py:320: AsdfWarning: Unable to locate schema file for 'tag:stsci.edu:jwst_pipeline/niriss-soss-0.7.0': 'http://stsci.edu/schemas/jwst_pipeline/niriss-soss-0.7.0'
```
There appears to be a mismatch (note the hyphen vs underscore) between the schema ID in the manifest:
https://github.com/spacetelescope/jwst/blob/67b11ff528c704757a42a7787ed6594228d342ac/jwst/transforms/resources/manifests/jwst_transforms-0.7.0.yaml#L47
and schema id in the schema file:
https://github.com/spacetelescope/jwst/blob/67b11ff528c704757a42a7787ed6594228d342ac/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_soss-0.7.0.yaml#L2

**Comment by tapastro** [comment]
Interesting, that appears to have been there for about a year. Is this from a test using oldest dependencies or with an up-to-date installation? There is a newer transform which should be used, `1.0.0`, which may be how this has been missed. I can correct it.

**Comment by braingram** [comment]
The warning was seen with the current master branch checked out (the pip freeze below shows in install from my fork which is up to date with 67b11ff as the most recent commit).

I'm not that familiar with this step (I found this issue while trying to replicate a different issue with a run of the jwst regression tests) so I might not be doing something correctly.

The use of the 0.7.0 tag appears in `atoca_extras_calints.fits` generated during the run of calwebb_spec2 using the following:
```python
from jwst.stpipe import Step


rtdata_input="atoca_extras_rateints.fits"
args = ["calwebb_spec2", rtdata_input,
    ]
Step.from_cmdline(args)
```

My pip freeze is as follows:
```
asdf==2.14.2
asdf-astropy==0.3.0
asdf-coordinates-schemas==0.1.0
asdf-standard==1.0.3
asdf-transform-schemas==0.3.0
asdf-unit-schemas==0.1.0
asdf-wcs-schemas==0.1.1
astropy==5.2
attrs==22.1.0
BayesicFitting==3.0.1
certifi==2022.5.18.1
charset-normalizer==2.1.1
ci-watson==0.6.1
codecov==2.1.12
colorama==0.4.6
contourpy==1.0.6
coverage==6.5.0
crds==11.16.16
cycler==0.11.0
drizzle==1.13.6
exceptiongroup==1.0.4
filelock==3.8.2
flake8==6.0.0
fonttools==4.38.0
future==0.18.2
getch==1.0
gwcs==0.18.2
idna==3.4
imageio==2.22.4
iniconfig==1.1.1
jmespath==1.0.1
jsonschema==4.17.3
-e git+ssh://git@github.com/braingram/jwst@67b11ff528c704757a42a7787ed6594228d342ac#egg=jwst
kiwisolver==1.4.4
lxml==4.9.2
matplotlib==3.6.2
mccabe==0.7.0
networkx==2.8.8
numpy==1.23.5
packaging==22.0
Parsley==1.3
photutils==1.6.0
Pillow==9.3.0
pluggy==1.0.0
poppy==1.0.3
psutil==5.9.4
pycodestyle==2.10.0
pyerfa==2.0.0.1
pyflakes==3.0.1
pyparsing==3.0.9
pyrsistent==0.19.2
pytest==7.2.0
pytest-cov==4.0.0
pytest-doctestplus==0.12.1
pytest-openfiles==0.5.0
python-dateutil==2.8.2
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.1
requests-mock==1.10.0
scikit-image==0.19.3
scipy==1.9.3
semantic-version==2.10.0
six==1.16.0
spherical-geometry==1.2.23
stcal==1.2.2
stdatamodels==0.4.3
stpipe==0.4.3
stsci.image==2.3.5
stsci.imagestats==1.6.3
stsci.stimage==0.2.6
tifffile==2022.10.10
tomli==2.0.1
tweakwcs==0.8.0
urllib3==1.26.13
wiimatch==0.3.1
```

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/jwst/pull/7450/

**Comment by WilliamJamieson** [comment]
There are actually more subtle issues at play than just the mismatch between the id listed in the manifest and what the schema lists.

These are being covered up by the issue reported. The converter is listing only hyphenated tag not the underscore tag. This is why the warning is still appearing even though we should be using the 1.0.0 schema/tag. This is because the converter can only write out niriss-soss tags not niriss_soss tags.

So the fix is not a "typo" fix. It's more complicated. #7450 also updated the tag in the manifest which is a mistake because that will break compatibility with any previously written files which contain that tag. Instead the only the schema_id field should be updated. Which should fix the schema not found warning.

As for actually fixing jwst so that it uses the 1.0.0 schema, that will require the converter to be updated to include the niriss_soss tag in it's possible tags and the supporting code to select the correct tag 1.0.0 when writing the code.

Note it's possible that we have been writing data under the 0.7.0 tag when it's actually 1.0.0 data. This could possibly be bad if 1.0.0 data is not valid under the 1.0.0 schema, though I haven't checked the schemas yet to definitively know the answers to this. In any case, we have essentially been reading and writing this data without proper validation for sometime, which is concerning.
